package datascope

var CompositeFields = map[string][]string{
	"ALL": {
		"Accrual Date",
		"Accrued Interest",
		"Asset Category",
		"Asset Status Effective Date",
		"Asset Status",
		"Asset SubType",
		"Asset Type",
		"Base Currency Code",
		"Bond Exchange List",
		"CIN Code",
		"Clean Price",
		"Close Price Timestamp",
		"Close Price",
		"Common Code",
		"Contributor Code",
		"Country of Incorporation",
		"Country of Issuance",
		"Country of Risk - All",
		"Country of Risk - Primary",
		"Country of Risk - Ultimate Parent - All",
		"Country of Risk - Ultimate Parent - Primary",
		"Country of Risk Date",
		"Coupon Frequency",
		"Coupon Rate Effective Date",
		"Coupon Rate",
		"Coupon Type",
		"Covered Bond Flag",
		"Currency Code",
		"Current Yield To Maturity",
		"Current Yield",
		"CUSIP",
		"Day Count Code",
		"Days To Expiration",
		"Days To Settle",
		"Debt Type",
		"Delay Days",
		"Denomination Increment",
		"Denomination Type",
		"Effective Date",
		"Entity LEI",
		"Ex-dividend Calendar",
		"Ex-dividend Rule",
		"Ex-dividend Value",
		"Exchange Code",
		"Exchange Country Code",
		"Exchange Region Code",
		"Expiration Date",
		"Factor Date",
		"Factor",
		"Final Coupon Date",
		"First Coupon Date",
		"First Trade Date",
		"Generic Price 1",
		"Generic Price 2",
		"Government Bond Type Code",
		"Government Bond Type Code Description",
		"Guarantee Flag",
		"Guarantor Type Code",
		"Guarantor LEI",
		"Guarantor Name",
		"Index Linked Bond Base Index",
		"Index Linked Bond Index Ratio",
		"Index-Linked Principal Flag",
		"Industry Sector Code",
		"Industry Sub-Sector Code",
		"Inflation Flag",
		"Inflation Protected Flag",
		"ISIN",
		"ISO Country Code",
		"Issue PermID",
		"Issuer Name",
		"Issuer OrgID",
		"Last Coupon Date",
		"Last Trading Day",
		"Maturity Date",
		"Minimum Denomination",
		"Moodys Issuer Long Rating",
		"Moodys Rating Date",
		"Moodys Rating",
		"Next Call Date",
		"Next Pay Date",
		"Price Quote Base Value",
		"Price Quote Convention",
		"Price Quote Method Code",
		"Price Quote Rounding",
		"Primary Quotation Exchange Country Code",
		"Quoted Clean Indicator",
		"Record Date Code",
		"Record Date Value",
		"Region Code",
		"RIC",
		"S&P Issuer Long Rating",
		"S&P Rating",
		"S&P Rating Date",
		"Security Description",
		"Security Long Name",
		"SEDOL",
		"Settlement Adjusted Index Ratio",
		"Settlement Date Convention",
		"Settlement Date",
		"Sinkable Flag",
		"Strike Price",
		"Ticker",
		"Trade Date",
		"Ultimate Parent LEI",
		"Ultimate Parent Official Name",
		"Ultimate Parent OrgID",
		"Underlying RIC",
		"Underlying Security Description",
		"Universal Close Price Date",
		"Universal Close Price",
		"User Defined Identifier",
		"Wertpapier",
	},
	"DEFAULT": {
		"Asset Type",
		"Base Currency Code",
		"Close Price",
		"Common Code",
		"Contributor Code",
		"Currency Code",
		"CUSIP",
		"Entity LEI",
		"Exchange Code",
		"Exchange Country Code",
		"Exchange Region Code",
		"ISIN",
		"ISO Country Code",
		"Issuer Name",
		"Issuer OrgID",
		"RIC",
		"Security Description",
		"Security Long Name",
		"Ticker",
		"Trade Date",
		"Ultimate Parent LEI",
		"Ultimate Parent Official Name",
		"Ultimate Parent OrgID",
		"Universal Close Price Date",
		"Universal Close Price",
		"User Defined Identifier",
		"Wertpapier",
	},
}

var EndOfDayFields = map[string][]string{
	"ALL": {
		"RIC",
		"Currency Code",
		"Trade Date",
		"Exchange Code",
		"Universal Close Price",
		"Discount Factor",
		"Zero Yield",
	},
	"DEFAULT": {
		"RIC",
		"Currency Code",
		"Trade Date",
		"Exchange Code",
		"Universal Close Price",
		"Universal Close Price Date",
	},
}

var PriceHistoryFields = map[string][]string{
	"DEFAULT": {
		"RIC",
		"Currency Code",
		"Trade Date",
		"Universal Close Price",
	},
}

var IntradayFields = map[string][]string{
	"DEFAULT": {
		"Europe Close Date",
		"Europe Close Price",
		"Last Price",
		"Exchange Code",
		"Official Close Date",
		"Official Close Price",
		"Primary Activity",
		"Trade Date",
		"Trade Time",
		"User Defined Identifier",
		"Value Date",
	},
}

var CorporateActionsFields = map[string][]string{
	"DEFAULT": {
		"Capital Change Announcement Date",
		"Capital Change Ex Date",
		"Effective Date",
		"Record Date",
		"Capital Change Event Type",
		"Old Shares Terms",
		"New Shares Terms",
		"New Shares Currency",
		"Dividend Announcement Date",
		"Dividend Currency",
		"Dividend Ex Date",
		"Dividend Rate",
	},
}
